a='S. A hil@ null 2006'
print('\n\n',a.upper(),sep='')
print(a.lower())
print(a.capitalize())
print(a.title())
print(a.rstrip('6'))
print(a.strip('S'))
print(a.lstrip("S.A"))
print(a.split(' '))
print(a.replace('hil','hir'))
print(a.center(100))
print(a.count('l'))
print(a.endswith('2006',0,len(a)))
print(a.startswith('l',7,8))
print(a.find('hil'))
print(a.index('nu'))
print(a.isalnum())
print(a.isalpha())
print(a.isascii())
print(a.islower())
print(a.isupper())
print(a.isprintable()) # for escape sequence character
print(a.isspace())
print(a.istitle())
print(a.swapcase())